### ISSUE TITLE
BUG REPORT 2

### ISSUE THREAD

**Issue by Amanzv** [NEST-Protocol/NEST-Protocol-Website#3]
a monitoring application was available on a remotely accessible administrative console in the nest staging environment, which could have been used to leverage information that could have compromised the server. 
kindly fix this by forbid the public access 

vulnerable url - https://me.nestdapp.io/druid/index.html

Best,
Amannoobda
<img width="1440" alt="Screenshot 2021-12-10 at 4 17 26 PM" src="https://user-images.githubusercontent.com/30231868/145562001-533a23b4-cf3a-4910-a4bb-37e9a605e441.png">

**Comment by MLY0813** [comment]
> 

Great find, we are redeveloping this site and plan to deploy it on S3 or IPFS. Not using a server is more in line with the definition of web3.
